The Red Hat Universal Base Image (UBI) is produced by Red Hat and is an
easy place to start when containerizing applications. If you want to
read more about the UBI program, or the three different flavors of UBI,
check out the https://developers.redhat.com/articles/ubi-faq[FAQ -
Universal Base Images] for additional details.

In this lab, you will be installing additional software into the
container image, however that software runs as an interactive
application. So you will need `+dnf+`, but do not need `+systemd+` for
managing services within the container environment. For that reason, you
will be using the *Standard* UBI image (as opposed to the Minimal or
Multi-service images).

By executing the command below, your system will download the Standard
UBI image from Red Hat’s registry.

[source,bash]
----
buildah from registry.access.redhat.com/ubi9/ubi
----

Trying to pull registry.access.redhat.com/ubi9/ubi:latest… Getting image
source signatures Checking if image destination supports signatures
Copying blob 7b3dd25bf011 done Copying config 663a35613b done Writing
manifest to image destination Storing signatures ubi-working-container
```

From the output above, you can see that the image was successfully
downloaded and a working container image was created and attached to the
system with the name of *ubi-working-container*. You will use this
working container in the next steps to install additional software
packages into the image.
